Repository Py-Contributors/AlgorithmsAndDataStructure, pull requests merged in 2020-10, with the labels that each got.

#427 Added Exponential Search Algorithm
  Python/Algorithms/SearchingAlgorithms/ExponentialSearch.py
Labels: hacktober-accepted

#423 Implemented Tree DS #55
  Python/DataStructure/TreeDS/TreeDS.py
Labels: hacktober-accepted

#378 Added code for Pancake_sort
  Python/Algorithms/SortingAlgorithms/pancake_sort.py
Labels: hacktober-accepted

#553 Added Cocktail Sort Algorithm in Python
  Python/Algorithms/SortingAlgorithms/CocktailSort.py
Labels: hacktober-accepted, hacktoberfest

#625 added topological sorting
  C++/Data Structure/Graph/Topological_Sorting.cpp
Labels: hacktober-accepted

#653 Added code for the maximum pairwise product problem
  C++/Algorithms/Maths/maxPairwiseProduct.cpp
Labels: hacktober-accepted

#743 Added Tim Sort Algorithm
  Python/Algorithms/SortingAlgorithms/TimSort.py
Labels: hacktober-accepted

#742 Add files via upload
  Python/Algorithms/SearchingAlgorithms/JumpSearch.py
Labels: hacktoberfest-accepted
